add stow task

diff --git a/scripts/bin/dotfiles b/scripts/bin/dotfiles
--- a/scripts/bin/dotfiles
+++ b/scripts/bin/dotfiles
@@ -14,11 +14,12 @@ if ! command -v git &> /dev/null; then
   sudo dnf install git-all -y
 fi
 
+# // TODO: clone at ~/.dotfiles
 # Clone .dotfiles 
-git clone https://github.com/nlulic/.dotfiles.git 
-status=$?
+# git clone https://github.com/nlulic/.dotfiles.git 
+# status=$?
 
-if [ $status -ne 0 ]; then
-    echo "Failed to clone dotfiles"
-    exit $status
-fi
+# if [ $status -ne 0 ]; then
+#     echo "Failed to clone dotfiles"
+#     exit $status
+# fi
